### ISSUE TITLE
Move @done items?

### ISSUE THREAD

**Issue by fitzage** [davidoc/taskpaper.vim#1]
I think a great feature would be to move items tagged as done to the bottom of their respective projects.

**Comment by davidoc** [comment]
I can see that this could be useful (although I sometimes like to preserve the ordering of tasks in a project). I'll keep it in mind, but I'm afraid I don't have much time to spend on taskpaper.vim at present.

Thanks!

**Comment by thesaneone** [comment]
I have implemented something like this, I will commit the changes once it's ready.

**Comment by jgallen23** [comment]
In one of the recent pull requests, there's an archive tasks (\tD)

**Comment by thesaneone** [comment]
Hmm, that was a year ago :) I had committed those changes - https://github.com/thesaneone/taskpaper.vim/commit/b36f38d988cbbc868ded43a4047fa3c1caa9e65b. Not sure everyone would want this - my archive tasks would move tasks to a configurable file.

**Comment by davidoc** [comment]
The current code archives @done tasks in an Archive: project and adds a tag like @project(Example Project) to indicate the original project. 

I'm going to mark this closed for now...
