### ISSUE TITLE
Enter always creates sub-tasks

### ISSUE THREAD

**Issue by marlun** [davidoc/taskpaper.vim#11]
Hi,

When I've written a task and hit <enter> to write another one, the new one is always automatically indented as a sub-task. Is this by design or is it something I've done? I would really like it to add another task with the same indenting.

**Comment by marlun** [comment]
I thought I could fix this by disabling autoindent but that only worked for the first level of projects and tasks. When I added a subproject and hit ENTER the new task only got one indentation level which put it on the same level as the project. Not sure how to solve this.

**Comment by davidoc** [comment]
Hi,

Thanks, I'll take a look. The intention was that after typing a Project: heading the next line would be a task, and hitting enter after that would give another task at the same level.

I'll see if I have the same problem you reported.

David

**Comment by gcman105** [comment]
I'm having this problem too.

**Comment by gre** [comment]
IMO binding the ENTER key is a bad idea because it breaks how you do "return" in VIM.
Why not switching with Shift + Enter (which seems to be the real ENTER) ?
Or otherwise how can we do it in our vimrc ?

Thanks

**Comment by brandoniffert** [comment]
Any fix for this yet or at least a workaround?

**Comment by davidoc** [comment]
The script that controls how carriage return is handled is in after/plugin/taskpaper.vim. For me 
- I don't have the problem of each task being a sub-task of (i.e. indented further than) the previous task
- I do have the problem that sub-tasks of sub-projects have the same indentation as the sub-project heading.

You can disable the automatic creation of new tasks on carriage return by removing after/plugin/taskpaper.vim (or commenting out the contents)

**Comment by brandoniffert** [comment]
Thanks. I rarely make subtasks so turning all indenting off `set noai nocin nosi inde=` works for me.

**Comment by davidoc** [comment]
Current master handles carriage returns in a sane way. After typing a project heading and hitting <CR> it will start a task (tab, hyphen). Otherwise, it maintains the current indent.

Thanks to anyakichi, for this.
