### ISSUE TITLE
Backtrace error when trying to cancel or complete

### ISSUE THREAD

**Issue by ghost** [davidoc/taskpaper.vim#13]
Whenever I hit <Leader>td or similar I get a backtrace error.
Ideas on what could be causing this?

**Comment by davidoc** [comment]
Hi,

On 19 Apr 2011, at 16:09, dsr wrote:

> Whenever I hit <Leader>td or similar I get a backtrace error.
> Ideas on what could be causing this?

Sorry, no...

Could you include the error message?

David

## 

Ánra Taighde - Scoil na hEolaíochta Ríomhaireachta ⁊ na Staitisticí,
 Coláiste na Tríonóide, Baile Átha Cliath 2 
Research Fellow - School of Computer Science & Statistics,
 Trinity College, Dublin 2          Guthán / Telephone: +353 1 896 1720

**Comment by ghost** [comment]
I think it ended up being something unrelated. I have it working now. Thanks.

Dan
