### ISSUE TITLE
Folding not working as expected

### ISSUE THREAD

**Issue by nshram** [davidoc/taskpaper.vim#20]
Hello David!

I'm a new user of your taskpaper vim plugin. I use it under Ubuntu 10.04.
I followed your instructions('taskpaper.txt') as well as those given in the google groups post - regarding making a 'filetype plugin indent on' entry in ~/.vimrc. I also added a 'set fdm=syntax' entry in ~/.vimrc. (which, as i found later, was not required).

Now \ta, \tx, \td and \tc work as expected.
But,

\tp folds up the WHOLE project/task hierarchy, leaving only the FIRST project line visible. It's not leaving ALL project lines visible.

zc folds up ALL the project and task lines BELOW the cursor, leaving only the project line ABOVE or ON the cursor visible. Intended is that it will fold only ONE project - the one where the cursor is stationed on.

zo behaves likewise, just reversing the effect of zc.

What am i missing here?

**Comment by davidoc** [comment]
Hi, I want to confirm that there's an issue with sub-projects. If your file has sub-projects (indented projects) then the \tp folding mechanism fails. If you can try a file with only top-level projects \tp should work as expected. I'm working on the solution.

**Comment by nshram** [comment]
Hello, David!

I created a file with only top level projects. But I still see the same
behaviour. I have attached the file.

Regards

Shankar Ram

On Wed, Feb 8, 2012 at 2:32 AM, David O'Callaghan <
reply@reply.github.com

**Comment by davidoc** [comment]
I've improved the folding behaviour (I think!). It now only attempts to fold top-level (i.e. un-indented) projects. All sub-projects will get folded into their top-level project. Can you try installing the current version from github?

(Note, I've made the format a little more strictly compatible with TaskPaper: tabs must be used for indents)

**Comment by nshram** [comment]
Hello David!

I have tested your latest version of the taskpaper plugin.
It works as intended: \tp folds all top level projects. \ta unfolds all.
\zc & \zo fold and unfold the top level project under the cursor.

One small observation: If there is a top level project without any tasks or
sub-projects, it is untouched and it's colours remain as is. Which i
suppose is ok. I can't think of any better way to handle such "empty"
projects.

Really great!

Now for sub-projects...!

Regards

Shankar Ram

On Wed, Feb 8, 2012 at 3:43 PM, David O'Callaghan <
reply@reply.github.com
