### ISSUE TITLE
\tt seems to be broken

### ISSUE THREAD

**Issue by cj** [davidoc/taskpaper.vim#25]
I'm using the latest version. When I use `\tt` nothing happens, but `\td` works just fine.

p.s. thank you for this great script

**Comment by nshram** [comment]
works for me!?

**Comment by davidoc** [comment]
Works in current master version (i.e. it adds a `@today` tag). Please follow up if it's still a problem.

**Comment by cj** [comment]
The latest version fixed everything :D  Thank you.

p.s. Is it possible to add the time a task was completed as well as the date when doing `\td`?

**Comment by davidoc** [comment]
@cj You can customise the date format. For example, in your .vimrc put:

```
let g:task_paper_date_format = "%Y-%m-%dT%H:%M:%S%z"
```
