### ISSUE TITLE
Indenting issues

### ISSUE THREAD

**Issue by cj** [davidoc/taskpaper.vim#26]
If I hit return I would have thought for it to create a new line under the same indentation, except it indents further in i.e.

![](https://dl.dropbox.com/u/71697/jing/2012-02-19_1711.png)

Also how do I change the indentation to just 2 spaces instead of a full tab?

**Comment by nshram** [comment]
i think you have set autoindent on in your .vimrc! that will cause this behaviour.
for changing indentation to 2 spaces put set tabstop=2 in your .vimrc. this will still write a tab into the file but display it as 2 spaces. if you want 2 spaces in the file, it may not work under taskpaper for iOS/mac.

**Comment by cj** [comment]
@nshram thank you for your reply.  I have everything setup correctly, this is my .vimrc https://github.com/cj/dotfiles :smile:  I think it's something else....

**Comment by cj** [comment]
I found the place it sets 4 width:

``` ruby
augroup taskpaper
     au! BufRead,BufNewFile *.taskpaper   setfiletype taskpaper
     au FileType taskpaper setlocal noexpandtab shiftwidth=4 tabstop=4
augroup END
```

in ftdetect.  Still not sure why it keeps indenting the way it does.

**Comment by davidoc** [comment]
The current master version doesn't set the shiftwidth or tabstop, and hitting return works as you would expect.

To preserve compatibility with the TaskPaper application, a real tab is required to indent tasks, sub-projects, etc. If you want tabs to _appear_ smaller, you can :set `tabstop=2 softtabstop=2` (either in the ftdetect for taskpaper files, or in .vimrc for all.)
