### ISSUE TITLE
Enter key behaviour

### ISSUE THREAD

**Issue by nshram** [davidoc/taskpaper.vim#28]
Hello David!
Thanks to you and anyakichi for a whole raft of improvements.

I refer to your comments with regard to issue #11:
"Current master handles carriage returns in a sane way. After typing a project heading and hitting it will start a task (tab, hyphen). Otherwise, it maintains the current indent.

Thanks to anyakichi, for this."

My inclination is: 
1 enter after a project should map to: <tab><hyphen><space>, while maintaining current indent, of course
2 enter after a task should map to: <hyphen><space>, while maintaining current indent
3 enter after a note should just maintain current indent
4 enter at the top level, i.e at extreme left column, should just maintain current indent

This almost matches the behaviour of the iOS version of taskpaper.

I tried putting back the "after" folder from your earlier versions and fiddling with it, but wasn't entirely successful!

I know this may not be to everybody's liking, so... how do i customize or tweak this change myself?

**Comment by nshram** [comment]
Yikes! The markdown parsing removed some of the stuff! (How do i bypass it?)
Here it is again:
1 enter after a project should map to: tab hyphen space, while maintaining current indent, of course
2 enter after a task should map to: hyphen space, while maintaining current indent
3 enter after a note should just maintain current indent
4 enter at the top level, i.e at extreme left column, should just maintain current indent

**Comment by anyakichi** [comment]
Hmm, I think the current behavior is just as you like if 'autoindent' or 'smartindent' is on.

If you mean the normal mode behavior, try this:

<pre>
nmap &lt;buffer&gt; &lt;CR&gt; &lt;Plug&gt;TaskPaperNewline
</pre>


I recommend to use the "o" command simply, though.

**Comment by nshram** [comment]
Not so! If autoindent is on, it only takes care of maintaining the current indent. 
But hypen + space is added _**only**_ for the first line after a project.
normal mode behaviour too doesn't do this.
So, adding set autoindent into the plugin files somewhere will take care of points 1,3,4 but not 2.
I'm sure this could be tweaked in as an option.

**Comment by anyakichi** [comment]
Oh, I see!  Try ":set fo+=rol" after opening taskpaper file.
I didn't realize that because this was already in my .vimrc.
I will fix this.

Probably, ":set textwidth=0" is also suitable for taskpaper.

**Comment by nshram** [comment]
Hello anyakichi!
":set fo+=rol" works!
":set textwidth=0" doesn't.
Thanks for your superfast response and solution.

**Comment by anyakichi** [comment]
Fixed on my master.  Pull it up, David!

**Comment by nshram** [comment]
Hello anyakichi!
I had manually modified the 'taskpaper.vim' file in /ftplugin to match the changes you had made. However, When I did the same in David's recent merging of pull request #29, the following doesn't work:
3 enter after a note should just maintain current indent
4 enter at the top level, i.e at extreme left column, should just maintain current indent

**Comment by anyakichi** [comment]
Hmm, the fix of the #29 seems to be wrong for both changes...
The current version of my master should work for you.

**Comment by nshram** [comment]
Well... ok! 

But I do feel that this behaviour of enter key is useful. Also, it is very close to the behaviour of the original taskpaper application. So, I hope David or you will find a way to merge this into the main version!

To restate and recap:
1. Enter after a project gives CR autoindent tab hyphen space
2. Enter after a task gives CR autoindent hyphen space
3. Enter after a note just gives CR autoindent
4. Enter when in 1st column just gives a CR

**Comment by davidoc** [comment]
I've merged  anyakichi's latest master (and sorry for being slow to respond!)

**Comment by nshram** [comment]
Great work, David! Everything required as above works fine. This plugin really rocks now - thanks to you and all the other contributors. :-)
