### ISSUE TITLE
Nested Projects Issue

### ISSUE THREAD

**Issue by jgallen23** [davidoc/taskpaper.vim#31]
taskpaper#go_to_project() and taskpaper#move() don't work with nested projects

fyi to @anyakichi since they did most of the work (amazing job btw).

**Comment by anyakichi** [comment]
The first argument of taskpaper#move() must be a list of a project tree.
When you move the item on the cursor, call taskpaper#move() like:

<pre>
:call taskpaper#move(['Project', 'Sub Project'])
</pre>


Of course, you can create the mapping for it.

And when you call taskpaper#go_to_project(), vim should prompt you for project
name.  If you jump to a sub-project here, type like:

<pre>
Project: Project:Sub project
</pre>


A sub-project is specified as colon separated form of the project tree.
You can complete a project name with Tab and you can see candidates with
&lt;C-d&gt;.

**Comment by jgallen23** [comment]
Well that's awesome.  Closing.

**Comment by davidoc** [comment]
Great stuff. I'm going to merge your master into mine.
