### ISSUE TITLE
help not working

### ISSUE THREAD

**Issue by nshram** [davidoc/taskpaper.vim#35]
:help taskpaper not working in latest release (0c30991)
was/is working ok in release 0d97323
did the usual :helptags ~/.vim/doc

**Comment by nshram** [comment]
Found the reason: /doc/taskpaper.txt needs to have string _taskpaper_ at the start of the file!

**Comment by nshram** [comment]
that markdown again! i meant, string "taskpaper" surrounded by asterisks!

**Comment by nshram** [comment]
like so: ***_taskpaper**_*

**Comment by davidoc** [comment]
Thanks. Strange: I thought I was _fixing_ the format, in the last commit...
