### ISSUE TITLE
TaskPaper does not recognize "-" to create tasks

### ISSUE THREAD

**Issue by ghost** [davidoc/taskpaper.vim#4]
TaskPaper does not recognize "-" from vim (using taskpaper.vim) to create or properly format tasks. The line intended to be a task is interpreted by TaskPaper as a note even though the hyphen is present.

I'm guessing tasks are not being recognized because TaskPaper's behavior has somehow changed to autoformat tasks when it see a hyphen. Not sure if a fix is possible from the taskpaper.vim perspective. I'll file this with the developer as well.

**Comment by davidoc** [comment]
Thanks, I'll see if I can compare the behaviour.

**Comment by ghost** [comment]
I think Taskpaper must expect a tab and not spaces. My vim settings convert tabs to spaces. I would expect this is not entirely uncommon.

**Comment by davidoc** [comment]
Hi, this has been addressed by a change I introduced this morning that forces tabs to use tab characters (noexpandtab). If you already have a taskpaper file with spaces then you will need to replace them with tabs (e.g. in Vim replace four spaces with a tab `:%s/    /\t/gc`)

I haven't yet tested the resulting files in TaskPaper on a Mac.

**Comment by ghost** [comment]
Thanks for the update. Just tested on Mac. Works great if I hit tab 2x. Looks like the plugin is looking for 4 spaces to force a tab. Since I have tabs set at 2 spaces the plugin does not see them as tabs. Hitting tab twice isn't a huge pain, and it's nice to have something working.

**Comment by davidoc** [comment]
You can try modifying the settings in ftdetect/taskpaper.vim and altering shiftwidth=2 and softtabstop=2 so that one press of the tab button actually inserts a tab for you.
