### ISSUE TITLE
Sub-Projects not Highlighted/Coloured

### ISSUE THREAD

**Issue by krid78** [davidoc/taskpaper.vim#49]
Sub-projects in a tp-File are not highlighted. I checked the corresponding regular expression, but it seems to catch all tasks. I played around with the groups, but did not get it to work. Can others here reproduce this issue?

**Comment by jhacksworth** [comment]
Sub-projects are highlighted for me.

As you probably know, if there is trailing space after the colon then the project is not highlighted.

**Comment by krid78** [comment]
Oh - well - that's not the problem. I did a short check and I realized, that everything works well if I do a `:setf taskpaper` after starting vim.
That worked in a new buffer as well as with one of my existing files.

**Comment by krid78** [comment]
Ok - here is my minimal example. I tried the following:
- remove condition from vim-plug Plug instruction
- remove ftplugin with personalizations

It remains. If I do `:setf taskpaper` highlighting works as expected. On fresh loaded file, only top level projects get highlighted. Furthermore, projects marked as `@done` are not highlighted as well.

[minimal.taskpaper.txt](https://github.com/davidoc/taskpaper.vim/files/45253/minimal.taskpaper.txt)

**Comment by krid78** [comment]
Ok, I found the reason for the nonworking highlighting. It's due to IndentLine from @Yggdroot. If I disable this plugin, everything works as expected. Thus I guess, the characters introduced to show the indentation levels interfere with the regular expressions for the task paper indentation.

Does anyone have an idea, how to overcome this in a generic way? Currently, I use `let g:indentLine_fileTypeExclude = ['taskpaper']` to avoid enabling the IndentLine for task paper-files.
