### ISSUE TITLE
Archive @done projects adds garbled @project tags

### ISSUE THREAD

**Issue by courtyardz** [davidoc/taskpaper.vim#54]
A task marked `@done` in project `inbox`:

     inbox:
          - troubleshoot problem X @done(2018-03-31T17:35:29-0400)

Upon archival this gets turned into:

    archive:
        - troubleshoot problem X @done(2018-03-31T17:35:29-0400) @project(inbox / - troubleshoot problem X @done(2018-03-31T17)

As you can see, the newly appended @project tag never gets closed, and the task becomes unnecessarily reprinted.  I will try to reinstall taskpaper.vim, in case I fuddled with the source long ago. But can someone point me to the plugin's code that handles archiving?  I searched around the vim script functions in `taskpaper.vim/autoload/taskpaper.vim` with not much illumination.

**Comment by courtyardz** [comment]
Yea..... I recloned and the issue persists :(

**Comment by ghost** [comment]
I think that's a bug. I think it's seeing the first : in the @done timestamp as a nested project (hence the nested project ends at 17). Try removing the time from the timestamp or replacing the : with something else, maybe a .

**Comment by courtyardz** [comment]
Thanks and good catch @RayDrew49, I replaced the colons with periods and the parsing works now.
